cutadapt_output: "/data/luka.lenaroto/eDentity/sequencer_tender/cutadapt-output/illumina"

raw_data: "/data/luka.lenaroto/eDentity/sequencer_tender/241008_VH00147_37_AAG3LFWM5/Analysis/2/Data/fastq"

